import os
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
from langchain.text_splitter import RecursiveCharacterTextSplitter

class DataLoader:
    def __init__(self, model_name='all-MiniLM-L6-v2'):
        """
        Initializes the DataLoader with a specific SentenceTransformer model.
        Default model 'all-MiniLM-L6-v2' has a dimension of 384.
        """
        self.model = SentenceTransformer(model_name)
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000,
            chunk_overlap=100
        )

    def load_pdf(self, file_path):
        """
        Loads a PDF file and extracts text from all pages.
        Includes handling for empty pages and logging for extraction results.
        """
        reader = PdfReader(file_path)
        text = ""
        total_pages = len(reader.pages)
        extracted_pages = 0
        
        for i, page in enumerate(reader.pages):
            page_text = page.extract_text()
            if page_text and page_text.strip():
                text += page_text + "\n"
                extracted_pages += 1
        
        extracted_text = text.strip()
        char_count = len(extracted_text)
        print(f"--- Extraction Details ---")
        print(f"Pages: {extracted_pages}/{total_pages}")
        print(f"Total Characters: {char_count}")
        if char_count > 0:
            snippet = extracted_text[:100].replace('\n', ' ')
            print(f"Snippet: {snippet}...")
        print(f"--------------------------")
        
        return extracted_text

    def split_text(self, text):
        """
        Splits text into smaller chunks for processing.
        Returns an empty list if no text is provided.
        """
        if not text:
            return []
        
        chunks = self.text_splitter.split_text(text)
        print(f"Split into {len(chunks)} chunks.")
        return chunks



    def get_embeddings(self, text_chunks):
        """
        Generates embeddings for a list of text chunks.
        """
        embeddings = self.model.encode(text_chunks)
        return embeddings.tolist()

    @property
    def embedding_dimension(self):
        """
        Returns the dimension of the embeddings generated by the model.
        """
        return self.model.get_sentence_embedding_dimension()

